version: '3'
services:
  app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - mongoserver

  mongoserver:
    image: mongo:6.0
    ports:
      - "27025:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
